name: gRPC Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test-Code-Update:
    
    runs-on: ubuntu-18.04
    
    steps:
      
      - name: Get source code into virtual machine
        uses: actions/checkout@v2
        
      - name: Setup the master branch 
        uses: r-lib/actions/setup-r@master
        with:
            r-version: '3.6.1'
      
      - name: Install Dependencies
        uses: ktmud/cached-dependencies@v1
        with:
          caches: ${{ github.workspace }}/.github/configs/caches.js
          bashlib: ${{ github.workspace }}/.github/configs/bashlib.sh
          run: |
          
            cache-restore openssl
            
            cache-restore proto

            cache-restore grpc_base
            
