name: gRPC Continuous Integration 1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test-Code-Update:
    
    runs-on: ubuntu-18.04
    
    steps:
      
      - name: Get source code into virtual machine
        uses: actions/checkout@v2
        
      - name: Setup the master branch 
        uses: r-lib/actions/setup-r@master
        with:
            r-version: '3.6.1'
          
      - name: Cache grpc_base
        uses: actions/cache@v1
        id: cache-grpc_base
        with:
          path: "~/grpc_base"
          key: "grpc_base"
          
      - name: Install grpc_base
        env:
          CACHE_HIT: ${{steps.cache-grpc_base.outputs.cache-hit}}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/grpc_base/* /
          else
            sudo apt-get install libcurl4-openssl-dev
            sudo apt-get install libprotoc-dev
            git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc grpc_base
          fi
