name: gRPC Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test-Code-Update:
    
    runs-on: ubuntu-18.04
    
    steps:
      
      - name: Get source code into virtual machine
        uses: actions/checkout@v2
        
      - name: Setup the master branch 
        uses: r-lib/actions/setup-r@master
        with:
            r-version: '3.6.1'
      
      - name: Install Dependencies
        run: |
          
          sudo apt-get install libcurl4-openssl-dev
          
          sudo apt-get install libprotoc-dev
          
          git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc grpc_base
