name: gRPC Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test Code Update:
    runs-on: ubuntu-18.04
    steps:
      
      - name: Get Source Code into Virtual Machine
        uses: actions/checkout@v2
