name: gRPC Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev libxml2-dev
          R -e 'install.packages("remotes")'
          R -e 'install.packages("devtools")'
          brew install protobuf
          R -e 'install_github("eddelbuettel/rprotobuf")'
          R -e 'remotes::install_deps(dependencies = TRUE)'
          R -e 'remotes::install_cran("covr")'
          R -e 'covr::codecov()'
