name: Client-Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev libxml2-dev
          R -e 'demo("helloserver")'
